### ISSUE TITLE
Structuring the project

### ISSUE THREAD

**Issue by SvantjeJung** [SvantjeJung/battleship#1]
We need two players, as it should be played over network one player must host the server that communicates with the players. 
At least two possibilities: 
1. The server-player waits for a client-player to connect.
2. The server waits for two arbitrary players to connect.

Server and client must be designed separately.

**Comment by Varaion** [comment]
Id go with option 1. That way we wouldnt need server space as the first player will provide that function.
It might be a bit more complex to get the connection that way though.

**Comment by SvantjeJung** [comment]
Suggestion for project framework has been made on the default working branch `dev`. Any comments welcome. If structure is okay for the time being, I would suggest to push the initialization to the `master` branch.

**Comment by Varaion** [comment]
Looks good to me.
